---
title: "The tidytext practice"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = TRUE, message=FALSE, warning=FALSE,
    fig.align='center', fig.height=7, fig.width=7, fig.dpi=300, 
    cache=TRUE
)
```

## Intuitive

[tidy text mining](http://tidytextmining.com/tidytext.html)에 서술된 내용을 따라해 보는 코드이다. 


```{r}
library(dplyr)

text <- c("Because I could not stop for Death -",
          "He kindly stopped for me -",
          "The Carriage held but just Ourselves -",
          "and Immortality")

text

text_df <- data_frame(line = 1:4, text = text)

text_df

library(tidytext)

text_df %>%
  unnest_tokens(word, text)

```


## Works 1

```{r}
library(janeaustenr)
library(dplyr)
library(stringr)

original_books <- austen_books() %>%
  group_by(book) %>%
  mutate(linenumber = row_number(),
         chapter = cumsum(str_detect(text, regex("^chapter [\\divxlc]",                                                 ignore_case = TRUE)))) %>%
  ungroup()

original_books


library(tidytext)

tidy_books <- original_books %>%
  unnest_tokens(word, text)

tidy_books

data(stop_words)

tidy_books <- tidy_books %>%
  anti_join(stop_words)

tidy_books %>%
  count(word, sort=TRUE)

library(ggplot2)

tidy_books %>%
  count(word, sort=TRUE) %>%
  filter(n > 600) %>%
  mutate(word=record(word, n)) %>%
  ggplot( aes(word,n) ) + 
  geom_col() +
  xlab(NULL) + 
  cord_flip()
```


